introduction: |-
        [Cloud Pub/Sub](https://cloud.google.com/pubsub/docs) is a fully-managed real-time messaging service that allows
        you to send and receive messages between independent applications.
