// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as gax from 'google-gax';
import {
  APICallback,
  Callback,
  CallOptions,
  Descriptors,
  ClientOptions,
  PaginationCallback,
} from 'google-gax';
import * as path from 'path';

import {Transform} from 'stream';
import * as protosTypes from '../../protos/protos';
import * as gapicConfig from './publisher_client_config.json';
import {IamClient} from '../helper';

const version = require('../../../package.json').version;

/**
 *  The service that an application uses to manipulate topics, and to send
 *  messages to a topic.
 * @class
 * @memberof v1
 */
export class PublisherClient {
  private _descriptors: Descriptors = {
    page: {},
    stream: {},
    longrunning: {},
    batching: {},
  };
  private _innerApiCalls: {[name: string]: Function};
  private _pathTemplates: {[name: string]: gax.PathTemplate};
  private _terminated = false;
  private _iamClient: IamClient;
  private _opts: ClientOptions;
  private _gaxModule: typeof gax | typeof gax.fallback;
  private _gaxGrpc: gax.GrpcClient | gax.fallback.GrpcClient;
  private _protos: {};
  private _defaults: {[method: string]: gax.CallSettings};
  auth: gax.GoogleAuth;
  publisherStub?: Promise<{[name: string]: Function}>;

  /**
   * Construct an instance of PublisherClient.
   *
   * @param {object} [options] - The configuration object. See the subsequent
   *   parameters for more details.
   * @param {object} [options.credentials] - Credentials object.
   * @param {string} [options.credentials.client_email]
   * @param {string} [options.credentials.private_key]
   * @param {string} [options.email] - Account email address. Required when
   *     using a .pem or .p12 keyFilename.
   * @param {string} [options.keyFilename] - Full path to the a .json, .pem, or
   *     .p12 key downloaded from the Google Developers Console. If you provide
   *     a path to a JSON file, the projectId option below is not necessary.
   *     NOTE: .pem and .p12 require you to specify options.email as well.
   * @param {number} [options.port] - The port on which to connect to
   *     the remote host.
   * @param {string} [options.projectId] - The project ID from the Google
   *     Developer's Console, e.g. 'grape-spaceship-123'. We will also check
   *     the environment variable GCLOUD_PROJECT for your project ID. If your
   *     app is running in an environment which supports
   *     {@link https://developers.google.com/identity/protocols/application-default-credentials Application Default Credentials},
   *     your project ID will be detected automatically.
   * @param {string} [options.apiEndpoint] - The domain name of the
   *     API remote host.
   */

  constructor(opts?: ClientOptions) {
    // Ensure that options include the service address and port.
    const staticMembers = this.constructor as typeof PublisherClient;
    const servicePath =
      opts && opts.servicePath
        ? opts.servicePath
        : opts && opts.apiEndpoint
        ? opts.apiEndpoint
        : staticMembers.servicePath;
    const port = opts && opts.port ? opts.port : staticMembers.port;

    if (!opts) {
      opts = {servicePath, port};
    }
    opts.servicePath = opts.servicePath || servicePath;
    opts.port = opts.port || port;
    opts.clientConfig = opts.clientConfig || {};

    const isBrowser = typeof window !== 'undefined';
    if (isBrowser) {
      opts.fallback = true;
    }
    // If we are in browser, we are already using fallback because of the
    // "browser" field in package.json.
    // But if we were explicitly requested to use fallback, let's do it now.
    this._gaxModule = !isBrowser && opts.fallback ? gax.fallback : gax;

    // Create a `gaxGrpc` object, with any grpc-specific options
    // sent to the client.
    opts.scopes = (this.constructor as typeof PublisherClient).scopes;
    this._gaxGrpc = new this._gaxModule.GrpcClient(opts);

    // Save options to use in initialize() method.
    this._opts = opts;

    // Save the auth object to the client, for use by other methods.
    this.auth = this._gaxGrpc.auth as gax.GoogleAuth;

    this._iamClient = new IamClient(opts);
    // Determine the client header string.
    const clientHeader = [`gax/${this._gaxModule.version}`, `gapic/${version}`];
    if (typeof process !== 'undefined' && 'versions' in process) {
      clientHeader.push(`gl-node/${process.versions.node}`);
    } else {
      clientHeader.push(`gl-web/${this._gaxModule.version}`);
    }
    if (!opts.fallback) {
      clientHeader.push(`grpc/${this._gaxGrpc.grpcVersion}`);
    }
    if (opts.libName && opts.libVersion) {
      clientHeader.push(`${opts.libName}/${opts.libVersion}`);
    }
    // Load the applicable protos.
    // For Node.js, pass the path to JSON proto file.
    // For browsers, pass the JSON content.

    const nodejsProtoPath = path.join(
      __dirname,
      '..',
      '..',
      'protos',
      'protos.json'
    );
    this._protos = this._gaxGrpc.loadProto(
      opts.fallback ? require('../../protos/protos.json') : nodejsProtoPath
    );

    // This API contains "path templates"; forward-slash-separated
    // identifiers to uniquely identify resources within the API.
    // Create useful helper objects for these.
    this._pathTemplates = {
      projectTopicPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/topics/{topic}'
      ),
      snapshotPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/snapshots/{snapshot}'
      ),
      subscriptionPathTemplate: new this._gaxModule.PathTemplate(
        'projects/{project}/subscriptions/{subscription}'
      ),
    };

    // Some of the methods on this service return "paged" results,
    // (e.g. 50 results at a time, with tokens to get subsequent
    // pages). Denote the keys used for pagination and results.
    this._descriptors.page = {
      listTopics: new this._gaxModule.PageDescriptor(
        'pageToken',
        'nextPageToken',
        'topics'
      ),
      listTopicSubscriptions: new this._gaxModule.PageDescriptor(
        'pageToken',
        'nextPageToken',
        'subscriptions'
      ),
      listTopicSnapshots: new this._gaxModule.PageDescriptor(
        'pageToken',
        'nextPageToken',
        'snapshots'
      ),
    };

    // Put together the default options sent with requests.
    this._defaults = this._gaxGrpc.constructSettings(
      'google.pubsub.v1.Publisher',
      gapicConfig as gax.ClientConfig,
      opts.clientConfig || {},
      {'x-goog-api-client': clientHeader.join(' ')}
    );

    // Set up a dictionary of "inner API calls"; the core implementation
    // of calling the API is handled in `google-gax`, with this code
    // merely providing the destination and request information.
    this._innerApiCalls = {};
  }

  /**
   * Initialize the client.
   * Performs asynchronous operations (such as authentication) and prepares the client.
   * This function will be called automatically when any class method is called for the
   * first time, but if you need to initialize it before calling an actual method,
   * feel free to call initialize() directly.
   *
   * You can await on this method if you want to make sure the client is initialized.
   *
   * @returns {Promise} A promise that resolves to an authenticated service stub.
   */
  initialize() {
    // If the client stub promise is already initialized, return immediately.
    if (this.publisherStub) {
      return this.publisherStub;
    }

    // Put together the "service stub" for
    // google.pubsub.v1.Publisher.
    this.publisherStub = this._gaxGrpc.createStub(
      this._opts.fallback
        ? (this._protos as protobuf.Root).lookupService(
            'google.pubsub.v1.Publisher'
          )
        : // tslint:disable-next-line no-any
          (this._protos as any).google.pubsub.v1.Publisher,
      this._opts
    ) as Promise<{[method: string]: Function}>;

    // Iterate over each of the methods that the service provides
    // and create an API call method for each.
    const publisherStubMethods = [
      'createTopic',
      'updateTopic',
      'publish',
      'getTopic',
      'listTopics',
      'listTopicSubscriptions',
      'listTopicSnapshots',
      'deleteTopic',
    ];

    for (const methodName of publisherStubMethods) {
      const innerCallPromise = this.publisherStub.then(
        stub => (...args: Array<{}>) => {
          if (this._terminated) {
            return Promise.reject('The client has already been closed.');
          }
          const func = stub[methodName];
          return func.apply(stub, args);
        },
        (err: Error | null | undefined) => () => {
          throw err;
        }
      );

      const apiCall = this._gaxModule.createApiCall(
        innerCallPromise,
        this._defaults[methodName],
        this._descriptors.page[methodName] ||
          this._descriptors.stream[methodName] ||
          this._descriptors.longrunning[methodName]
      );

      this._innerApiCalls[methodName] = (
        argument: {},
        callOptions?: CallOptions,
        callback?: APICallback
      ) => {
        return apiCall(argument, callOptions, callback);
      };
    }

    return this.publisherStub;
  }

  /**
   * The DNS address for this API service.
   */
  static get servicePath() {
    return 'pubsub.googleapis.com';
  }

  /**
   * The DNS address for this API service - same as servicePath(),
   * exists for compatibility reasons.
   */
  static get apiEndpoint() {
    return 'pubsub.googleapis.com';
  }

  /**
   * The port for this API service.
   */
  static get port() {
    return 443;
  }

  /**
   * The scopes needed to make gRPC calls for every method defined
   * in this service.
   */
  static get scopes() {
    return [
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/pubsub',
    ];
  }

  getProjectId(): Promise<string>;
  getProjectId(callback: Callback<string, undefined, undefined>): void;
  /**
   * Return the project ID used by this class.
   * @param {function(Error, string)} callback - the callback to
   *   be called with the current project Id.
   */
  getProjectId(
    callback?: Callback<string, undefined, undefined>
  ): Promise<string> | void {
    if (callback) {
      this.auth.getProjectId(callback);
      return;
    }
    return this.auth.getProjectId();
  }

  // -------------------
  // -- Service calls --
  // -------------------
  createTopic(
    request: protosTypes.google.pubsub.v1.ITopic,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.ITopic | undefined,
      {} | undefined
    ]
  >;
  createTopic(
    request: protosTypes.google.pubsub.v1.ITopic,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.ITopic | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Creates the given topic with the given name. See the
   * <a href="https://cloud.google.com/pubsub/docs/admin#resource_names">
   * resource name rules</a>.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.name
   *   Required. The name of the topic. It must have the format
   *   `"projects/{project}/topics/{topic}"`. `{topic}` must start with a letter,
   *   and contain only letters (`[A-Za-z]`), numbers (`[0-9]`), dashes (`-`),
   *   underscores (`_`), periods (`.`), tildes (`~`), plus (`+`) or percent
   *   signs (`%`). It must be between 3 and 255 characters in length, and it
   *   must not start with `"goog"`.
   * @param {number[]} request.labels
   *   See <a href="https://cloud.google.com/pubsub/docs/labels"> Creating and
   *   managing labels</a>.
   * @param {google.pubsub.v1.MessageStoragePolicy} request.messageStoragePolicy
   *   Policy constraining the set of Google Cloud Platform regions where messages
   *   published to the topic may be stored. If not present, then no constraints
   *   are in effect.
   * @param {string} request.kmsKeyName
   *   The resource name of the Cloud KMS CryptoKey to be used to protect access
   *   to messages published on this topic.
   *
   *   The expected format is `projects/* /locations/* /keyRings/* /cryptoKeys/*`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Topic]{@link google.pubsub.v1.Topic}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  createTopic(
    request: protosTypes.google.pubsub.v1.ITopic,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.pubsub.v1.ITopic,
          protosTypes.google.pubsub.v1.ITopic | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.ITopic | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.ITopic | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      name: request.name || '',
    });
    this.initialize();
    return this._innerApiCalls.createTopic(request, options, callback);
  }
  updateTopic(
    request: protosTypes.google.pubsub.v1.IUpdateTopicRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IUpdateTopicRequest | undefined,
      {} | undefined
    ]
  >;
  updateTopic(
    request: protosTypes.google.pubsub.v1.IUpdateTopicRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IUpdateTopicRequest | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Updates an existing topic. Note that certain properties of a
   * topic are not modifiable.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {google.pubsub.v1.Topic} request.topic
   *   Required. The updated topic object.
   * @param {google.protobuf.FieldMask} request.updateMask
   *   Required. Indicates which fields in the provided topic to update. Must be
   *   specified and non-empty. Note that if `update_mask` contains
   *   "message_storage_policy" then the new value will be determined based on the
   *   policy configured at the project or organization level. The
   *   `message_storage_policy` must not be set in the `topic` provided above.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Topic]{@link google.pubsub.v1.Topic}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  updateTopic(
    request: protosTypes.google.pubsub.v1.IUpdateTopicRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.pubsub.v1.ITopic,
          protosTypes.google.pubsub.v1.IUpdateTopicRequest | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IUpdateTopicRequest | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IUpdateTopicRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      'topic.name': request.topic!.name || '',
    });
    this.initialize();
    return this._innerApiCalls.updateTopic(request, options, callback);
  }
  publish(
    request: protosTypes.google.pubsub.v1.IPublishRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.pubsub.v1.IPublishResponse,
      protosTypes.google.pubsub.v1.IPublishRequest | undefined,
      {} | undefined
    ]
  >;
  publish(
    request: protosTypes.google.pubsub.v1.IPublishRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.pubsub.v1.IPublishResponse,
      protosTypes.google.pubsub.v1.IPublishRequest | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Adds one or more messages to the topic. Returns `NOT_FOUND` if the topic
   * does not exist.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The messages in the request will be published on this topic.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {number[]} request.messages
   *   Required. The messages to publish.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [PublishResponse]{@link google.pubsub.v1.PublishResponse}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  publish(
    request: protosTypes.google.pubsub.v1.IPublishRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.pubsub.v1.IPublishResponse,
          protosTypes.google.pubsub.v1.IPublishRequest | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.pubsub.v1.IPublishResponse,
      protosTypes.google.pubsub.v1.IPublishRequest | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.pubsub.v1.IPublishResponse,
      protosTypes.google.pubsub.v1.IPublishRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    this.initialize();
    return this._innerApiCalls.publish(request, options, callback);
  }
  getTopic(
    request: protosTypes.google.pubsub.v1.IGetTopicRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IGetTopicRequest | undefined,
      {} | undefined
    ]
  >;
  getTopic(
    request: protosTypes.google.pubsub.v1.IGetTopicRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IGetTopicRequest | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Gets the configuration of a topic.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The name of the topic to get.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Topic]{@link google.pubsub.v1.Topic}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  getTopic(
    request: protosTypes.google.pubsub.v1.IGetTopicRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.pubsub.v1.ITopic,
          protosTypes.google.pubsub.v1.IGetTopicRequest | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IGetTopicRequest | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic,
      protosTypes.google.pubsub.v1.IGetTopicRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    this.initialize();
    return this._innerApiCalls.getTopic(request, options, callback);
  }
  deleteTopic(
    request: protosTypes.google.pubsub.v1.IDeleteTopicRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.protobuf.IEmpty,
      protosTypes.google.pubsub.v1.IDeleteTopicRequest | undefined,
      {} | undefined
    ]
  >;
  deleteTopic(
    request: protosTypes.google.pubsub.v1.IDeleteTopicRequest,
    options: gax.CallOptions,
    callback: Callback<
      protosTypes.google.protobuf.IEmpty,
      protosTypes.google.pubsub.v1.IDeleteTopicRequest | undefined,
      {} | undefined
    >
  ): void;
  /**
   * Deletes the topic with the given name. Returns `NOT_FOUND` if the topic
   * does not exist. After a topic is deleted, a new topic may be created with
   * the same name; this is an entirely new topic with none of the old
   * configuration or subscriptions. Existing subscriptions to this topic are
   * not deleted, but their `topic` field is set to `_deleted-topic_`.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. Name of the topic to delete.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is an object representing [Empty]{@link google.protobuf.Empty}.
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  deleteTopic(
    request: protosTypes.google.pubsub.v1.IDeleteTopicRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | Callback<
          protosTypes.google.protobuf.IEmpty,
          protosTypes.google.pubsub.v1.IDeleteTopicRequest | undefined,
          {} | undefined
        >,
    callback?: Callback<
      protosTypes.google.protobuf.IEmpty,
      protosTypes.google.pubsub.v1.IDeleteTopicRequest | undefined,
      {} | undefined
    >
  ): Promise<
    [
      protosTypes.google.protobuf.IEmpty,
      protosTypes.google.pubsub.v1.IDeleteTopicRequest | undefined,
      {} | undefined
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    this.initialize();
    return this._innerApiCalls.deleteTopic(request, options, callback);
  }

  listTopics(
    request: protosTypes.google.pubsub.v1.IListTopicsRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic[],
      protosTypes.google.pubsub.v1.IListTopicsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicsResponse
    ]
  >;
  listTopics(
    request: protosTypes.google.pubsub.v1.IListTopicsRequest,
    options: gax.CallOptions,
    callback: PaginationCallback<
      protosTypes.google.pubsub.v1.ITopic[],
      protosTypes.google.pubsub.v1.IListTopicsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicsResponse
    >
  ): void;
  /**
   * Lists matching topics.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. The name of the project in which to list topics.
   *   Format is `projects/{project-id}`.
   * @param {number} request.pageSize
   *   Maximum number of topics to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicsResponse`; indicates that this is
   *   a continuation of a prior `ListTopics` call, and that the system should
   *   return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is Array of [Topic]{@link google.pubsub.v1.Topic}.
   *   The client library support auto-pagination by default: it will call the API as many
   *   times as needed and will merge results from all the pages into this array.
   *
   *   When autoPaginate: false is specified through options, the array has three elements.
   *   The first element is Array of [Topic]{@link google.pubsub.v1.Topic} that corresponds to
   *   the one page received from the API server.
   *   If the second element is not null it contains the request object of type [ListTopicsRequest]{@link google.pubsub.v1.ListTopicsRequest}
   *   that can be used to obtain the next page of the results.
   *   If it is null, the next page does not exist.
   *   The third element contains the raw response received from the API server. Its type is
   *   [ListTopicsResponse]{@link google.pubsub.v1.ListTopicsResponse}.
   *
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  listTopics(
    request: protosTypes.google.pubsub.v1.IListTopicsRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | PaginationCallback<
          protosTypes.google.pubsub.v1.ITopic[],
          protosTypes.google.pubsub.v1.IListTopicsRequest | null,
          protosTypes.google.pubsub.v1.IListTopicsResponse
        >,
    callback?: PaginationCallback<
      protosTypes.google.pubsub.v1.ITopic[],
      protosTypes.google.pubsub.v1.IListTopicsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicsResponse
    >
  ): Promise<
    [
      protosTypes.google.pubsub.v1.ITopic[],
      protosTypes.google.pubsub.v1.IListTopicsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicsResponse
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    this.initialize();
    return this._innerApiCalls.listTopics(request, options, callback);
  }

  /**
   * Equivalent to {@link listTopics}, but returns a NodeJS Stream object.
   *
   * This fetches the paged responses for {@link listTopics} continuously
   * and invokes the callback registered for 'data' event for each element in the
   * responses.
   *
   * The returned object has 'end' method when no more elements are required.
   *
   * autoPaginate option will be ignored.
   *
   * @see {@link https://nodejs.org/api/stream.html}
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.project
   *   Required. The name of the project in which to list topics.
   *   Format is `projects/{project-id}`.
   * @param {number} request.pageSize
   *   Maximum number of topics to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicsResponse`; indicates that this is
   *   a continuation of a prior `ListTopics` call, and that the system should
   *   return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Stream}
   *   An object stream which emits an object representing [Topic]{@link google.pubsub.v1.Topic} on 'data' event.
   */
  listTopicsStream(
    request?: protosTypes.google.pubsub.v1.IListTopicsRequest,
    options?: gax.CallOptions
  ): Transform {
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      project: request.project || '',
    });
    const callSettings = new gax.CallSettings(options);
    this.initialize();
    return this._descriptors.page.listTopics.createStream(
      this._innerApiCalls.listTopics as gax.GaxCall,
      request,
      callSettings
    );
  }
  listTopicSubscriptions(
    request: protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      string[],
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsResponse
    ]
  >;
  listTopicSubscriptions(
    request: protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest,
    options: gax.CallOptions,
    callback: PaginationCallback<
      string[],
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsResponse
    >
  ): void;
  /**
   * Lists the names of the subscriptions on this topic.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The name of the topic that subscriptions are attached to.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {number} request.pageSize
   *   Maximum number of subscription names to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicSubscriptionsResponse`; indicates
   *   that this is a continuation of a prior `ListTopicSubscriptions` call, and
   *   that the system should return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is Array of string.
   *   The client library support auto-pagination by default: it will call the API as many
   *   times as needed and will merge results from all the pages into this array.
   *
   *   When autoPaginate: false is specified through options, the array has three elements.
   *   The first element is Array of string that corresponds to
   *   the one page received from the API server.
   *   If the second element is not null it contains the request object of type [ListTopicSubscriptionsRequest]{@link google.pubsub.v1.ListTopicSubscriptionsRequest}
   *   that can be used to obtain the next page of the results.
   *   If it is null, the next page does not exist.
   *   The third element contains the raw response received from the API server. Its type is
   *   [ListTopicSubscriptionsResponse]{@link google.pubsub.v1.ListTopicSubscriptionsResponse}.
   *
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  listTopicSubscriptions(
    request: protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | PaginationCallback<
          string[],
          protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest | null,
          protosTypes.google.pubsub.v1.IListTopicSubscriptionsResponse
        >,
    callback?: PaginationCallback<
      string[],
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsResponse
    >
  ): Promise<
    [
      string[],
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSubscriptionsResponse
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    this.initialize();
    return this._innerApiCalls.listTopicSubscriptions(
      request,
      options,
      callback
    );
  }

  /**
   * Equivalent to {@link listTopicSubscriptions}, but returns a NodeJS Stream object.
   *
   * This fetches the paged responses for {@link listTopicSubscriptions} continuously
   * and invokes the callback registered for 'data' event for each element in the
   * responses.
   *
   * The returned object has 'end' method when no more elements are required.
   *
   * autoPaginate option will be ignored.
   *
   * @see {@link https://nodejs.org/api/stream.html}
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The name of the topic that subscriptions are attached to.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {number} request.pageSize
   *   Maximum number of subscription names to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicSubscriptionsResponse`; indicates
   *   that this is a continuation of a prior `ListTopicSubscriptions` call, and
   *   that the system should return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Stream}
   *   An object stream which emits an object representing string on 'data' event.
   */
  listTopicSubscriptionsStream(
    request?: protosTypes.google.pubsub.v1.IListTopicSubscriptionsRequest,
    options?: gax.CallOptions
  ): Transform {
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    const callSettings = new gax.CallSettings(options);
    this.initialize();
    return this._descriptors.page.listTopicSubscriptions.createStream(
      this._innerApiCalls.listTopicSubscriptions as gax.GaxCall,
      request,
      callSettings
    );
  }
  listTopicSnapshots(
    request: protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest,
    options?: gax.CallOptions
  ): Promise<
    [
      string[],
      protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSnapshotsResponse
    ]
  >;
  listTopicSnapshots(
    request: protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest,
    options: gax.CallOptions,
    callback: PaginationCallback<
      string[],
      protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSnapshotsResponse
    >
  ): void;
  /**
   * Lists the names of the snapshots on this topic. Snapshots are used in
   * <a href="https://cloud.google.com/pubsub/docs/replay-overview">Seek</a>
   * operations, which allow
   * you to manage message acknowledgments in bulk. That is, you can set the
   * acknowledgment state of messages in an existing subscription to the state
   * captured by a snapshot.
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The name of the topic that snapshots are attached to.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {number} request.pageSize
   *   Maximum number of snapshot names to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicSnapshotsResponse`; indicates
   *   that this is a continuation of a prior `ListTopicSnapshots` call, and
   *   that the system should return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Promise} - The promise which resolves to an array.
   *   The first element of the array is Array of string.
   *   The client library support auto-pagination by default: it will call the API as many
   *   times as needed and will merge results from all the pages into this array.
   *
   *   When autoPaginate: false is specified through options, the array has three elements.
   *   The first element is Array of string that corresponds to
   *   the one page received from the API server.
   *   If the second element is not null it contains the request object of type [ListTopicSnapshotsRequest]{@link google.pubsub.v1.ListTopicSnapshotsRequest}
   *   that can be used to obtain the next page of the results.
   *   If it is null, the next page does not exist.
   *   The third element contains the raw response received from the API server. Its type is
   *   [ListTopicSnapshotsResponse]{@link google.pubsub.v1.ListTopicSnapshotsResponse}.
   *
   *   The promise has a method named "cancel" which cancels the ongoing API call.
   */
  listTopicSnapshots(
    request: protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest,
    optionsOrCallback?:
      | gax.CallOptions
      | PaginationCallback<
          string[],
          protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest | null,
          protosTypes.google.pubsub.v1.IListTopicSnapshotsResponse
        >,
    callback?: PaginationCallback<
      string[],
      protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSnapshotsResponse
    >
  ): Promise<
    [
      string[],
      protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest | null,
      protosTypes.google.pubsub.v1.IListTopicSnapshotsResponse
    ]
  > | void {
    request = request || {};
    let options: gax.CallOptions;
    if (typeof optionsOrCallback === 'function' && callback === undefined) {
      callback = optionsOrCallback;
      options = {};
    } else {
      options = optionsOrCallback as gax.CallOptions;
    }
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    this.initialize();
    return this._innerApiCalls.listTopicSnapshots(request, options, callback);
  }

  /**
   * Equivalent to {@link listTopicSnapshots}, but returns a NodeJS Stream object.
   *
   * This fetches the paged responses for {@link listTopicSnapshots} continuously
   * and invokes the callback registered for 'data' event for each element in the
   * responses.
   *
   * The returned object has 'end' method when no more elements are required.
   *
   * autoPaginate option will be ignored.
   *
   * @see {@link https://nodejs.org/api/stream.html}
   *
   * @param {Object} request
   *   The request object that will be sent.
   * @param {string} request.topic
   *   Required. The name of the topic that snapshots are attached to.
   *   Format is `projects/{project}/topics/{topic}`.
   * @param {number} request.pageSize
   *   Maximum number of snapshot names to return.
   * @param {string} request.pageToken
   *   The value returned by the last `ListTopicSnapshotsResponse`; indicates
   *   that this is a continuation of a prior `ListTopicSnapshots` call, and
   *   that the system should return the next page of data.
   * @param {object} [options]
   *   Call options. See {@link https://googleapis.dev/nodejs/google-gax/latest/interfaces/CallOptions.html|CallOptions} for more details.
   * @returns {Stream}
   *   An object stream which emits an object representing string on 'data' event.
   */
  listTopicSnapshotsStream(
    request?: protosTypes.google.pubsub.v1.IListTopicSnapshotsRequest,
    options?: gax.CallOptions
  ): Transform {
    request = request || {};
    options = options || {};
    options.otherArgs = options.otherArgs || {};
    options.otherArgs.headers = options.otherArgs.headers || {};
    options.otherArgs.headers[
      'x-goog-request-params'
    ] = gax.routingHeader.fromParams({
      topic: request.topic || '',
    });
    const callSettings = new gax.CallSettings(options);
    this.initialize();
    return this._descriptors.page.listTopicSnapshots.createStream(
      this._innerApiCalls.listTopicSnapshots as gax.GaxCall,
      request,
      callSettings
    );
  }
  // --------------------
  // -- Path templates --
  // --------------------

  /**
   * Return a fully-qualified projectTopic resource name string.
   *
   * @param {string} project
   * @param {string} topic
   * @returns {string} Resource name string.
   */
  projectTopicPath(project: string, topic: string) {
    return this._pathTemplates.projectTopicPathTemplate.render({
      project,
      topic,
    });
  }

  /**
   * Parse the project from ProjectTopic resource.
   *
   * @param {string} projectTopicName
   *   A fully-qualified path representing project_topic resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromProjectTopicName(projectTopicName: string) {
    return this._pathTemplates.projectTopicPathTemplate.match(projectTopicName)
      .project;
  }

  /**
   * Parse the topic from ProjectTopic resource.
   *
   * @param {string} projectTopicName
   *   A fully-qualified path representing project_topic resource.
   * @returns {string} A string representing the topic.
   */
  matchTopicFromProjectTopicName(projectTopicName: string) {
    return this._pathTemplates.projectTopicPathTemplate.match(projectTopicName)
      .topic;
  }

  /**
   * Return a fully-qualified snapshot resource name string.
   *
   * @param {string} project
   * @param {string} snapshot
   * @returns {string} Resource name string.
   */
  snapshotPath(project: string, snapshot: string) {
    return this._pathTemplates.snapshotPathTemplate.render({
      project,
      snapshot,
    });
  }

  /**
   * Parse the project from Snapshot resource.
   *
   * @param {string} snapshotName
   *   A fully-qualified path representing Snapshot resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromSnapshotName(snapshotName: string) {
    return this._pathTemplates.snapshotPathTemplate.match(snapshotName).project;
  }

  /**
   * Parse the snapshot from Snapshot resource.
   *
   * @param {string} snapshotName
   *   A fully-qualified path representing Snapshot resource.
   * @returns {string} A string representing the snapshot.
   */
  matchSnapshotFromSnapshotName(snapshotName: string) {
    return this._pathTemplates.snapshotPathTemplate.match(snapshotName)
      .snapshot;
  }

  /**
   * Return a fully-qualified subscription resource name string.
   *
   * @param {string} project
   * @param {string} subscription
   * @returns {string} Resource name string.
   */
  subscriptionPath(project: string, subscription: string) {
    return this._pathTemplates.subscriptionPathTemplate.render({
      project,
      subscription,
    });
  }

  /**
   * Parse the project from Subscription resource.
   *
   * @param {string} subscriptionName
   *   A fully-qualified path representing Subscription resource.
   * @returns {string} A string representing the project.
   */
  matchProjectFromSubscriptionName(subscriptionName: string) {
    return this._pathTemplates.subscriptionPathTemplate.match(subscriptionName)
      .project;
  }

  /**
   * Parse the subscription from Subscription resource.
   *
   * @param {string} subscriptionName
   *   A fully-qualified path representing Subscription resource.
   * @returns {string} A string representing the subscription.
   */
  matchSubscriptionFromSubscriptionName(subscriptionName: string) {
    return this._pathTemplates.subscriptionPathTemplate.match(subscriptionName)
      .subscription;
  }

  /**
   * Terminate the GRPC channel and close the client.
   *
   * The client will no longer be usable and all future behavior is undefined.
   */
  close(): Promise<void> {
    this.initialize();
    if (!this._terminated) {
      return this.publisherStub!.then(stub => {
        this._terminated = true;
        stub.close();
      });
    }
    return Promise.resolve();
  }
  /**
   * This part will be added into src/v1/key_management_service_client.ts by synth.py.
   * KMS service requires IAM client for [setIamPolicy, getIamPolicy, testIamPerssion] methods.
   * But we don't support it now in micro-generators for rerouting one service to another and mix them in.
   * New feature request link: [https://github.com/googleapis/gapic-generator-typescript/issues/315]
   *
   * So this is manually written for providing methods to the KMS client.
   * IamClient is created for KMS client in the constructor using src/helper.ts.
   * [setIamPolicy, getIamPolicy, testIamPerssion] methods are created which is calling the corresponding methods from IamClient in `helper.ts`.
   */

  getIamPolicy(
    request: protosTypes.google.iam.v1.GetIamPolicyRequest,
    options: gax.CallOptions,
    callback: protosTypes.google.iam.v1.IAMPolicy.GetIamPolicyCallback
  ) {
    return this._iamClient.getIamPolicy(request, options, callback);
  }
  setIamPolicy(
    request: protosTypes.google.iam.v1.SetIamPolicyRequest,
    options: gax.CallOptions,
    callback: protosTypes.google.iam.v1.IAMPolicy.SetIamPolicyCallback
  ) {
    return this._iamClient.setIamPolicy(request, options, callback);
  }
  testIamPermissions(
    request: protosTypes.google.iam.v1.TestIamPermissionsRequest,
    options: gax.CallOptions,
    callback?: protosTypes.google.iam.v1.IAMPolicy.TestIamPermissionsCallback
  ) {
    return this._iamClient.testIamPermissions(request, options, callback);
  }
}
